# Generated by Django 4.1 on 2022-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.TextField()),
                ('group_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars', models.IntegerField()),
                ('sana', models.TextField()),
                ('from_id', models.TextField()),
                ('to_id', models.TextField()),
            ],
        ),
    ]
