# Generated by Django 4.1 on 2022-08-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
        migrations.AlterModelTable(
            name='sanalar',
            table='sanalar',
        ),
    ]
