# Generated by Django 4.0.6 on 2022-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='channel_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
