# Generated by Django 4.0.6 on 2022-07-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_payment_account_account_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='tg_id',
            new_name='account_id',
        ),
    ]
