# Generated by Django 4.0.6 on 2022-07-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_tg_id_account_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='price',
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='crm.account'),
            preserve_default=False,
        ),
    ]
