# Generated by Django 4.0.6 on 2022-07-21 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_account_price_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='join',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='left',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
