# Generated by Django 4.0.6 on 2022-07-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_payment_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='lesson_number',
        ),
    ]
