# Generated by Django 4.0.6 on 2022-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_course_number_course_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.TextField(default='Kurs uchun tolov'),
        ),
    ]
