# Generated by Django 4.0.6 on 2022-07-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_course_number_student_alter_account_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='oquvchi_narxi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='start_course',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
