# Generated by Django 4.0.6 on 2022-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_account_start_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='delete_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
