# Generated by Django 4.0.6 on 2022-07-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_account_delete_account_delete_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='delete_cause',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
