# Generated by Django 4.0.6 on 2022-08-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_account_delete_cause'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created_at',)},
        ),
    ]
