# Generated by Django 4.1 on 2022-08-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='channel_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
