# Generated by Django 4.1 on 2022-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_course_is_active_alter_course_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='left',
            field=models.IntegerField(default=0),
        ),
    ]
